version: '3'

services:
  rottingresearch:
    build: .
    container_name: researchgpt
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
        OPENAI_API_KEY: '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'
        CLOUD_STORAGE_BUCKET:
    volumes:
      - .:/app
