version: '3'

services:
  researchgpt:
    container_name: researchgpt
    image: marshalmiller/researchgpt:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - FLASK_APP: "app"
      - APP_SECRET_KEY: "change_me"
      - OPENAI_API_KEY: 'OPENAI_API_KEY'
      - CLOUD_STORAGE_BUCKET: 'CLOUD_STORAGE_BUCKET'
    volumes:
      - app:/app
