version: '3'

services:
  rottingresearch:
    build: .
    container_name: researchgpt
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
        OPENAI_API_KEY: 'OPENAI_API_KEY'
        CLOUD_STORAGE_BUCKET: 'CLOUD_STORAGE_BUCKET'
    volumes:
      - .:/app
