version: '3'

services:
  rottingresearch:
    build: .
    container_name: researchgpt
    restart: always
    ports:
      - "5000:5000"
    environment:
        OPENAI_API_KEY: 'ypur key here'
        CLOUD_STORAGE_BUCKET:
    volumes:
      - .:/app
