version: '3'

services:
  rottingresearch:
    build: .
    container_name: researchgpt
    restart: always
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY:
    volumes:
      - .:/app
